- name: Deploy Django updates
  hosts: web
  become: yes
  vars:
    known_hosts_path: "{{ lookup('env', 'KNOWN_HOSTS_PATH') }}"
    dest_path: "{{ lookup('env', 'DEST_PATH') }}"
    chdir_path: "{{ lookup('env', 'CHDIR_PATH') }}"
    collectstatic_command: "{{ lookup('env', 'COLLECTSTATIC_COMMAND') }}"
    deploy_log_path: "{{ lookup('env', 'DEPLOY_LOG_PATH') }}"
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
  tasks:
    - name: Ensure gitlab.com is in known_hosts
      ansible.builtin.known_hosts:
        name: gitlab.com
        key: "{{ lookup('pipe', 'ssh-keyscan gitlab.com') }}"
        path: "{{ known_hosts_path }}"

    - name: Pull latest code
      become: no
      ansible.builtin.git:
        repo: 'git@gitlab.com:web-port/web_portfolio.git'
        dest: "{{ dest_path }}"
        version: main
        force: yes

    - name: Collect static files as www-data
      become: yes
      become_user: www-data
      args:
        chdir: "{{ chdir_path }}"
      command: "{{ collectstatic_command }}"

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Restart Gunicorn
      systemd:
        name: gunicorn
        state: restarted

    - name: Test Nginx config
      command: nginx -t

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted